events {}

http {
    upstream gateway_backend {
        server gateway:4000;
    }

    upstream client_backend {
        server client:7000;
    }

    upstream recovery_manager_backend {
        server recovery_manager:6000;
    }

    server {
        listen 4000;
        absolute_redirect off;

        location / {
            proxy_pass http://gateway_backend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 6000;
        absolute_redirect off;

        location / {
            proxy_pass http://recovery_manager_backend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 7000;
        absolute_redirect off;

        location / {
            proxy_pass http://client_backend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
